# UTS-2 My Songs for You

Easy (like Sunday Morning)
{{< video https://youtu.be/saaLW0jiiUE?si=rwqHf-eN2Grr-VAM >}}, with lyrics

Easy

[Verse 1]
Know it sounds funny
But I just can't stand the pain
Girl, I'm leaving you tomorrow
Seems to me, girl
You know I've done all I can
You see, I begged, stole, and I borrowed, yeah, ooh

[Chorus]
That's why I'm easy
I'm easy like Sunday morning
That's why I'm easy
I'm easy like Sunday morning

[Verse 2]
Why in the world would anybody put chains on me, yeah?
I've paid my dues to make it
Everybody wants me to be
What they want me to be
I'm not happy when I try to fake it, no, ooh

[Chorus]
That's why I'm easy (yeah)
I'm easy like Sunday morning, yeah
That's why I'm easy
I'm easy like Sunday morning

[Bridge]
I wanna be high, so high
I wanna be free to know the things I do are right
I wanna be free
Just me, oh babe
Ooh

[Chorus/Outro]
That's why I'm easy
I'm easy like Sunday morning, yeah
That's why I'm easy
I'm easy like Sunday morning, woah
'Cause I'm easy, woo
Easy like Sunday morning, yeah
'Cause I'm easy
Easy like Sunday morning, whoa

---

Heavy
{{< video https://youtu.be/1BCqCgamowo?si=8aeQFa16PlxKPm7R >}}, with lyrics

Heavy

[Verse 1]
I'm heavy
I'm by your side
Forget me
'Cause I know what I need
Like a loser like me could be fine
I'm heavy
Alone inside
Don't tell me what I want, what I need
Like a loser like me will be fine

[Pre-Chorus]
Maybe I'm living in my head
Maybe I'm living to pretend
Maybe I wanna stay in bed
Far from the weight of the world in my hands
'Cause they don't understand

[Chorus]
Is someone telling me don't get in the water?
What have I done?
I don't wanna get lost inside the color under my tongue
'Cause I don't wanna be in love with another
Even in another life
Can someone tell me it's alright to be covered
Underneath the covers? But I

[Verse 2]
No, I don't need to sleep anymore
Is someone banging at my door?
When I just wanna be alone?
Is someone banging at my door?
Je ne sais pas qui est ici

[Bridge]
Is someone banging at my door
When I just wanna be alone
Is someone banging at my door, door, door, door?

[Outro]
Door, door, door, door, at my door
Is someone banging at my door?
'Cause I just wanna be alone
Yeah, I just wanna be alone
(I just wanna be alone)
(Yeah, I just wanna be alone)
(I just wanna be alone)